import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/leave_request_model.dart';
import '../utils/admin_helpers.dart';

class PdfService {
  /// Generates a Daily Report PDF listing all leaves for a specific date
  Future<void> generateDailyReport(DateTime date, List<LeaveRequestModel> leaves) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.interRegular();
    final fontBold = await PdfGoogleFonts.interBold();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("Daily Leave Report", style: pw.TextStyle(font: fontBold, fontSize: 24)),
                    pw.Text(DateFormat('MMMM dd, yyyy').format(date), style: pw.TextStyle(font: font, fontSize: 16)),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              
              // Summary Stats
              pw.Row(
                children: [
                  _statBox("Total Leaves", "${leaves.length}", fontBold),
                  pw.SizedBox(width: 12),
                  _statBox("On-Duty", "${leaves.where((l) => l.leaveType == 'OD').length}", fontBold),
                  pw.SizedBox(width: 12),
                  _statBox("Casual", "${leaves.where((l) => l.leaveType == 'CL').length}", fontBold),
                ],
              ),
              pw.SizedBox(height: 24),

              // Table
              pw.Table.fromTextArray(
                context: context,
                border: null,
                headerStyle: pw.TextStyle(font: fontBold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.blue600),
                cellStyle: pw.TextStyle(font: font, fontSize: 10),
                cellAlignments: {
                  0: pw.Alignment.centerLeft,
                  1: pw.Alignment.centerLeft,
                  2: pw.Alignment.centerLeft, // Type
                  3: pw.Alignment.centerLeft, // Reason
                },
                headers: <String>['Name', 'ID', 'Type', 'Reason'],
                data: leaves.map((leave) => [
                  leave.userName,
                  leave.employeeId ?? 'N/A',
                  AdminHelpers.getLeaveName(leave.leaveType),
                  leave.reason,
                ]).toList(),
              ),
              
              pw.Spacer(),
              pw.Divider(),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text("Generated by LeaveX", style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500)),
                  pw.Text("Page ${context.pageNumber} of ${context.pagesCount}", style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500)),
                ]
              )
            ],
          );
        },
      ),
    );

    // Print/Share
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'LeaveReport_${DateFormat('yyyyMMdd').format(date)}',
    );
  }

  /// Generates a Batch PDF containing application forms for multiple requests
  Future<void> generateBatchApplications(List<LeaveRequestModel> requests) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.interRegular();
    final fontBold = await PdfGoogleFonts.interBold();

    for (var request in requests) {
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return _buildApplicationPage(context, request, font, fontBold);
          },
        ),
      );
    }

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Batch_Leave_Applications_${DateFormat('yyyyMMdd_HHmmss').format(DateTime.now())}',
    );
  }

  /// Generates a single Application Form PDF (Table Style - Matching User App)
  Future<void> generateApplicationPdf(LeaveRequestModel request) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.interRegular();
    final fontBold = await PdfGoogleFonts.interBold();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return _buildApplicationPage(context, request, font, fontBold);
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Application_${request.userName}_${DateFormat('yyyyMMdd').format(request.fromDate)}',
    );
  }

  /// Helper to build the Application Form Page (Shared Logic)
  pw.Widget _buildApplicationPage(pw.Context context, LeaveRequestModel request, pw.Font font, pw.Font fontBold) {
    // Logic for Day vs Days
    final isHalfDay = request.numberOfDays == 0.5;
    final isSingleDay = request.numberOfDays == 1.0 || isHalfDay;
    final durationText = isHalfDay ? "Half Day" : "${request.numberOfDays} ${request.numberOfDays == 1.0 ? 'Day' : 'Days'}";

    // Logic for Date Text
    String dateText;
    if (isSingleDay) {
      dateText = "on ${DateFormat('dd-MM-yyyy').format(request.fromDate)}";
    } else {
      dateText = "from ${DateFormat('dd-MM-yyyy').format(request.fromDate)} to ${DateFormat('dd-MM-yyyy').format(request.toDate)}";
    }

    // Header Info
    final appliedAt = request.createdAt; // Use createdAt as applied date
    final String leaveType = request.leaveType;
    final String reason = request.reason;
    final String userName = request.userName;
    final String? employeeId = request.employeeId;

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        // 🏫 HEADER
        pw.Center(
          child: pw.Column(
            children: [
              pw.Text("KONGU ENGINEERING COLLEGE", style: pw.TextStyle(font: fontBold, fontSize: 16)),
              pw.Text("(Autonomous)", style: pw.TextStyle(font: fontBold, fontSize: 10)),
              pw.Text("PERUNDURAI, ERODE - 638 060", style: pw.TextStyle(font: fontBold, fontSize: 10)),
              pw.SizedBox(height: 10),
              pw.Text("LEAVE APPLICATION FORM", style: pw.TextStyle(font: fontBold, fontSize: 12, decoration: pw.TextDecoration.underline)),
            ]
          )
        ),
        pw.SizedBox(height: 20),

        // 📋 APPLICANT DETAILS TABLE
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.black, width: 0.5),
          columnWidths: {
            0: const pw.FlexColumnWidth(1.2),
            1: const pw.FlexColumnWidth(2),
          },
          children: [
             _tableRow("Application No", request.id.substring(0, 8).toUpperCase(), font, fontBold), // Use part of ID
             _tableRow("Date of Application", DateFormat('dd-MM-yyyy').format(appliedAt), font, fontBold),
             _tableRow("Name of the Applicant", userName.toUpperCase(), font, fontBold),
             if (employeeId != null && employeeId != "0000")
               _tableRow("Employee ID", employeeId, font, fontBold),
             _tableRow("Type of Leave", AdminHelpers.getLeaveName(leaveType), font, fontBold),
             _tableRow("Period of Leave", dateText.replaceAll('on ', '').replaceAll('from ', ''), font, fontBold),
             _tableRow("No. of Days", durationText, font, fontBold),
             _tableRow("Reason for Leave", reason, font, fontBold),
          ]
        ),
        
        pw.SizedBox(height: 15),
        
        // Declaration
        pw.Text("Declaration:", style: pw.TextStyle(font: fontBold, fontSize: 10)),
        pw.SizedBox(height: 5),
        pw.Text(
          "I hereby request that the above leave may kindly be granted. I have made alternative arrangements for my duties during my absence.",
          style: pw.TextStyle(font: font, fontSize: 10),
          textAlign: pw.TextAlign.justify
        ),

        pw.Spacer(),

        // ✍️ SIGNATURES
        pw.Container(
          padding: const pw.EdgeInsets.only(top: 40, bottom: 20),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _signatureBox("Signature of the Staff", font),
              _signatureBox("Placement Admin", font),
              _signatureBox("Principal", font),
            ]
          )
        ),
      ],
    );
  }

  // Helper for Table Row
  pw.TableRow _tableRow(String label, String value, pw.Font font, pw.Font fontBold) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(label, style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey700)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(value, style: pw.TextStyle(font: fontBold, fontSize: 10)),
        ),
      ]
    );
  }

  // Helper for Signature Box
  pw.Widget _signatureBox(String title, pw.Font font) {
     return pw.Column(
       children: [
         pw.Container(width: 80, height: 1, color: PdfColors.black),
         pw.SizedBox(height: 4),
         pw.Text(title, style: pw.TextStyle(font: font, fontSize: 10)),
       ]
     );
  }

  pw.Widget _statBox(String label, String value, pw.Font font) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label, style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey600)),
          pw.Text(value, style: pw.TextStyle(font: font, fontSize: 16)),
        ]
      )
    );
  }
  
  pw.Widget _detailRow(String label, String value, pw.Font font, pw.Font fontBold) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 12),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(font: font, color: PdfColors.grey700)),
          pw.Text(value, style: pw.TextStyle(font: fontBold)),
        ]
      )
    );
  }
}
